// themes.js — 10 themes × 10 items = 100 items
const THEMES_DATA = [
  // ── Greetings ──────────────────────────────────────────────────────────────
  { id: 1,  theme: "greetings", emoji: "👋", english: "Hello",        chinese: "你好",   pinyin: "nǐ hǎo",      audioText: "你好" },
  { id: 2,  theme: "greetings", emoji: "🙏", english: "Thank you",    chinese: "谢谢",   pinyin: "xiè xiè",     audioText: "谢谢" },
  { id: 3,  theme: "greetings", emoji: "😊", english: "Good morning", chinese: "早上好", pinyin: "zǎo shàng hǎo", audioText: "早上好" },
  { id: 4,  theme: "greetings", emoji: "🌙", english: "Good night",   chinese: "晚安",   pinyin: "wǎn ān",      audioText: "晚安" },
  { id: 5,  theme: "greetings", emoji: "👍", english: "Yes",          chinese: "是",     pinyin: "shì",         audioText: "是" },
  { id: 6,  theme: "greetings", emoji: "🙅", english: "No",           chinese: "不",     pinyin: "bù",          audioText: "不" },
  { id: 7,  theme: "greetings", emoji: "🤝", english: "Please",       chinese: "请",     pinyin: "qǐng",        audioText: "请" },
  { id: 8,  theme: "greetings", emoji: "😄", english: "Sorry",        chinese: "对不起", pinyin: "duì bù qǐ",   audioText: "对不起" },
  { id: 9,  theme: "greetings", emoji: "👋🏻", english: "Goodbye",      chinese: "再见",   pinyin: "zài jiàn",    audioText: "再见" },
  { id: 10, theme: "greetings", emoji: "🙋", english: "My name is",   chinese: "我叫",   pinyin: "wǒ jiào",     audioText: "我叫" },

  // ── Numbers 1–10 ───────────────────────────────────────────────────────────
  { id: 11, theme: "numbers", emoji: "1️⃣", english: "One",   chinese: "一", pinyin: "yī",   audioText: "一" },
  { id: 12, theme: "numbers", emoji: "2️⃣", english: "Two",   chinese: "二", pinyin: "èr",   audioText: "二" },
  { id: 13, theme: "numbers", emoji: "3️⃣", english: "Three", chinese: "三", pinyin: "sān",  audioText: "三" },
  { id: 14, theme: "numbers", emoji: "4️⃣", english: "Four",  chinese: "四", pinyin: "sì",   audioText: "四" },
  { id: 15, theme: "numbers", emoji: "5️⃣", english: "Five",  chinese: "五", pinyin: "wǔ",   audioText: "五" },
  { id: 16, theme: "numbers", emoji: "6️⃣", english: "Six",   chinese: "六", pinyin: "liù",  audioText: "六" },
  { id: 17, theme: "numbers", emoji: "7️⃣", english: "Seven", chinese: "七", pinyin: "qī",   audioText: "七" },
  { id: 18, theme: "numbers", emoji: "8️⃣", english: "Eight", chinese: "八", pinyin: "bā",   audioText: "八" },
  { id: 19, theme: "numbers", emoji: "9️⃣", english: "Nine",  chinese: "九", pinyin: "jiǔ",  audioText: "九" },
  { id: 20, theme: "numbers", emoji: "🔟", english: "Ten",   chinese: "十", pinyin: "shí",  audioText: "十" },

  // ── Colors ─────────────────────────────────────────────────────────────────
  { id: 21, theme: "colors", emoji: "🔴", english: "Red",    chinese: "红色", pinyin: "hóng sè", audioText: "红色" },
  { id: 22, theme: "colors", emoji: "🔵", english: "Blue",   chinese: "蓝色", pinyin: "lán sè",  audioText: "蓝色" },
  { id: 23, theme: "colors", emoji: "🟡", english: "Yellow", chinese: "黄色", pinyin: "huáng sè", audioText: "黄色" },
  { id: 24, theme: "colors", emoji: "🟢", english: "Green",  chinese: "绿色", pinyin: "lǜ sè",   audioText: "绿色" },
  { id: 25, theme: "colors", emoji: "🟠", english: "Orange", chinese: "橙色", pinyin: "chéng sè", audioText: "橙色" },
  { id: 26, theme: "colors", emoji: "🟣", english: "Purple", chinese: "紫色", pinyin: "zǐ sè",   audioText: "紫色" },
  { id: 27, theme: "colors", emoji: "⚫", english: "Black",  chinese: "黑色", pinyin: "hēi sè",  audioText: "黑色" },
  { id: 28, theme: "colors", emoji: "⚪", english: "White",  chinese: "白色", pinyin: "bái sè",  audioText: "白色" },
  { id: 29, theme: "colors", emoji: "🩷", english: "Pink",   chinese: "粉色", pinyin: "fěn sè",  audioText: "粉色" },
  { id: 30, theme: "colors", emoji: "🤎", english: "Brown",  chinese: "棕色", pinyin: "zōng sè", audioText: "棕色" },

  // ── Animals ────────────────────────────────────────────────────────────────
  { id: 31, theme: "animals", emoji: "🐶", english: "Dog",      chinese: "狗",  pinyin: "gǒu",    audioText: "狗" },
  { id: 32, theme: "animals", emoji: "🐱", english: "Cat",      chinese: "猫",  pinyin: "māo",    audioText: "猫" },
  { id: 33, theme: "animals", emoji: "🐭", english: "Mouse",    chinese: "老鼠", pinyin: "lǎo shǔ", audioText: "老鼠" },
  { id: 34, theme: "animals", emoji: "🐸", english: "Frog",     chinese: "青蛙", pinyin: "qīng wā", audioText: "青蛙" },
  { id: 35, theme: "animals", emoji: "🐷", english: "Pig",      chinese: "猪",  pinyin: "zhū",    audioText: "猪" },
  { id: 36, theme: "animals", emoji: "🐮", english: "Cow",      chinese: "牛",  pinyin: "niú",    audioText: "牛" },
  { id: 37, theme: "animals", emoji: "🐔", english: "Chicken",  chinese: "鸡",  pinyin: "jī",     audioText: "鸡" },
  { id: 38, theme: "animals", emoji: "🐻", english: "Bear",     chinese: "熊",  pinyin: "xióng",  audioText: "熊" },
  { id: 39, theme: "animals", emoji: "🐼", english: "Panda",    chinese: "熊猫", pinyin: "xióng māo", audioText: "熊猫" },
  { id: 40, theme: "animals", emoji: "🐟", english: "Fish",     chinese: "鱼",  pinyin: "yú",     audioText: "鱼" },

  // ── Food ───────────────────────────────────────────────────────────────────
  { id: 41, theme: "food", emoji: "🍚", english: "Rice",    chinese: "米饭", pinyin: "mǐ fàn",   audioText: "米饭" },
  { id: 42, theme: "food", emoji: "🍜", english: "Noodles", chinese: "面条", pinyin: "miàn tiáo", audioText: "面条" },
  { id: 43, theme: "food", emoji: "🥚", english: "Egg",     chinese: "鸡蛋", pinyin: "jī dàn",   audioText: "鸡蛋" },
  { id: 44, theme: "food", emoji: "🍎", english: "Apple",   chinese: "苹果", pinyin: "píng guǒ", audioText: "苹果" },
  { id: 45, theme: "food", emoji: "🍌", english: "Banana",  chinese: "香蕉", pinyin: "xiāng jiāo", audioText: "香蕉" },
  { id: 46, theme: "food", emoji: "🥛", english: "Milk",    chinese: "牛奶", pinyin: "niú nǎi",  audioText: "牛奶" },
  { id: 47, theme: "food", emoji: "🍞", english: "Bread",   chinese: "面包", pinyin: "miàn bāo", audioText: "面包" },
  { id: 48, theme: "food", emoji: "🍊", english: "Orange",  chinese: "橙子", pinyin: "chéng zi", audioText: "橙子" },
  { id: 49, theme: "food", emoji: "🥦", english: "Broccoli", chinese: "西兰花", pinyin: "xī lán huā", audioText: "西兰花" },
  { id: 50, theme: "food", emoji: "🍬", english: "Candy",   chinese: "糖果", pinyin: "táng guǒ", audioText: "糖果" },

  // ── Family ─────────────────────────────────────────────────────────────────
  { id: 51, theme: "family", emoji: "👨", english: "Dad",           chinese: "爸爸", pinyin: "bà ba",    audioText: "爸爸" },
  { id: 52, theme: "family", emoji: "👩", english: "Mom",           chinese: "妈妈", pinyin: "mā ma",    audioText: "妈妈" },
  { id: 53, theme: "family", emoji: "👦", english: "Brother",       chinese: "哥哥", pinyin: "gē ge",    audioText: "哥哥" },
  { id: 54, theme: "family", emoji: "👧", english: "Sister",        chinese: "姐姐", pinyin: "jiě jie",  audioText: "姐姐" },
  { id: 55, theme: "family", emoji: "👴", english: "Grandpa",       chinese: "爷爷", pinyin: "yé ye",    audioText: "爷爷" },
  { id: 56, theme: "family", emoji: "👵", english: "Grandma",       chinese: "奶奶", pinyin: "nǎi nai",  audioText: "奶奶" },
  { id: 57, theme: "family", emoji: "👶", english: "Baby",          chinese: "宝宝", pinyin: "bǎo bao",  audioText: "宝宝" },
  { id: 58, theme: "family", emoji: "🧑", english: "Child",         chinese: "孩子", pinyin: "hái zi",   audioText: "孩子" },
  { id: 59, theme: "family", emoji: "👨‍👩‍👦", english: "Family",        chinese: "家人", pinyin: "jiā rén",  audioText: "家人" },
  { id: 60, theme: "family", emoji: "🏠", english: "Home",          chinese: "家",   pinyin: "jiā",      audioText: "家" },

  // ── School Items ───────────────────────────────────────────────────────────
  { id: 61, theme: "school", emoji: "📚", english: "Book",    chinese: "书",  pinyin: "shū",     audioText: "书" },
  { id: 62, theme: "school", emoji: "✏️", english: "Pencil",  chinese: "铅笔", pinyin: "qiān bǐ", audioText: "铅笔" },
  { id: 63, theme: "school", emoji: "🎒", english: "Backpack", chinese: "书包", pinyin: "shū bāo", audioText: "书包" },
  { id: 64, theme: "school", emoji: "📏", english: "Ruler",   chinese: "尺子", pinyin: "chǐ zi",  audioText: "尺子" },
  { id: 65, theme: "school", emoji: "✂️", english: "Scissors", chinese: "剪刀", pinyin: "jiǎn dāo", audioText: "剪刀" },
  { id: 66, theme: "school", emoji: "🖍️", english: "Crayon",  chinese: "蜡笔", pinyin: "là bǐ",   audioText: "蜡笔" },
  { id: 67, theme: "school", emoji: "📐", english: "Triangle", chinese: "三角板", pinyin: "sān jiǎo bǎn", audioText: "三角板" },
  { id: 68, theme: "school", emoji: "🗒️", english: "Notebook", chinese: "本子", pinyin: "běn zi",  audioText: "本子" },
  { id: 69, theme: "school", emoji: "🖊️", english: "Pen",     chinese: "笔",  pinyin: "bǐ",      audioText: "笔" },
  { id: 70, theme: "school", emoji: "🏫", english: "School",  chinese: "学校", pinyin: "xué xiào", audioText: "学校" },

  // ── Body Parts ─────────────────────────────────────────────────────────────
  { id: 71, theme: "body", emoji: "👁️", english: "Eye",    chinese: "眼睛", pinyin: "yǎn jīng", audioText: "眼睛" },
  { id: 72, theme: "body", emoji: "👂", english: "Ear",    chinese: "耳朵", pinyin: "ěr duo",   audioText: "耳朵" },
  { id: 73, theme: "body", emoji: "👃", english: "Nose",   chinese: "鼻子", pinyin: "bí zi",    audioText: "鼻子" },
  { id: 74, theme: "body", emoji: "👄", english: "Mouth",  chinese: "嘴巴", pinyin: "zuǐ bā",   audioText: "嘴巴" },
  { id: 75, theme: "body", emoji: "🦷", english: "Teeth",  chinese: "牙齿", pinyin: "yá chǐ",   audioText: "牙齿" },
  { id: 76, theme: "body", emoji: "✋", english: "Hand",   chinese: "手",   pinyin: "shǒu",     audioText: "手" },
  { id: 77, theme: "body", emoji: "🦶", english: "Foot",   chinese: "脚",   pinyin: "jiǎo",     audioText: "脚" },
  { id: 78, theme: "body", emoji: "🫀", english: "Heart",  chinese: "心脏", pinyin: "xīn zàng", audioText: "心脏" },
  { id: 79, theme: "body", emoji: "🧠", english: "Brain",  chinese: "大脑", pinyin: "dà nǎo",   audioText: "大脑" },
  { id: 80, theme: "body", emoji: "💪", english: "Arm",    chinese: "手臂", pinyin: "shǒu bì",  audioText: "手臂" },

  // ── Feelings ───────────────────────────────────────────────────────────────
  { id: 81, theme: "feelings", emoji: "😊", english: "Happy",   chinese: "快乐", pinyin: "kuài lè",  audioText: "快乐" },
  { id: 82, theme: "feelings", emoji: "😢", english: "Sad",     chinese: "伤心", pinyin: "shāng xīn", audioText: "伤心" },
  { id: 83, theme: "feelings", emoji: "😡", english: "Angry",   chinese: "生气", pinyin: "shēng qì", audioText: "生气" },
  { id: 84, theme: "feelings", emoji: "😨", english: "Scared",  chinese: "害怕", pinyin: "hài pà",   audioText: "害怕" },
  { id: 85, theme: "feelings", emoji: "😴", english: "Sleepy",  chinese: "困",   pinyin: "kùn",      audioText: "困" },
  { id: 86, theme: "feelings", emoji: "🤒", english: "Sick",    chinese: "生病", pinyin: "shēng bìng", audioText: "生病" },
  { id: 87, theme: "feelings", emoji: "😎", english: "Cool",    chinese: "酷",   pinyin: "kù",       audioText: "酷" },
  { id: 88, theme: "feelings", emoji: "🥰", english: "Love",    chinese: "爱",   pinyin: "ài",       audioText: "爱" },
  { id: 89, theme: "feelings", emoji: "😲", english: "Surprised", chinese: "惊讶", pinyin: "jīng yà", audioText: "惊讶" },
  { id: 90, theme: "feelings", emoji: "😌", english: "Calm",    chinese: "平静", pinyin: "píng jìng", audioText: "平静" },

  // ── Actions ────────────────────────────────────────────────────────────────
  { id: 91, theme: "actions", emoji: "🏃", english: "Run",   chinese: "跑",   pinyin: "pǎo",     audioText: "跑" },
  { id: 92, theme: "actions", emoji: "🚶", english: "Walk",  chinese: "走",   pinyin: "zǒu",     audioText: "走" },
  { id: 93, theme: "actions", emoji: "🍽️", english: "Eat",   chinese: "吃",   pinyin: "chī",     audioText: "吃" },
  { id: 94, theme: "actions", emoji: "💧", english: "Drink", chinese: "喝",   pinyin: "hē",      audioText: "喝" },
  { id: 95, theme: "actions", emoji: "😴", english: "Sleep", chinese: "睡觉", pinyin: "shuì jiào", audioText: "睡觉" },
  { id: 96, theme: "actions", emoji: "📖", english: "Read",  chinese: "读",   pinyin: "dú",      audioText: "读" },
  { id: 97, theme: "actions", emoji: "✏️", english: "Write", chinese: "写",   pinyin: "xiě",     audioText: "写" },
  { id: 98, theme: "actions", emoji: "🎵", english: "Sing",  chinese: "唱歌", pinyin: "chàng gē", audioText: "唱歌" },
  { id: 99, theme: "actions", emoji: "💃", english: "Dance", chinese: "跳舞", pinyin: "tiào wǔ", audioText: "跳舞" },
  { id: 100, theme: "actions", emoji: "🤗", english: "Hug",   chinese: "拥抱", pinyin: "yōng bào", audioText: "拥抱" },
];

const THEME_META = {
  greetings: { label: "Greetings",    emoji: "👋", color: "#FF6B6B" },
  numbers:   { label: "Numbers",      emoji: "🔢", color: "#FF9F43" },
  colors:    { label: "Colors",       emoji: "🌈", color: "#FECA57" },
  animals:   { label: "Animals",      emoji: "🐾", color: "#48DBFB" },
  food:      { label: "Food",         emoji: "🍎", color: "#FF9FF3" },
  family:    { label: "Family",       emoji: "👨‍👩‍👦", color: "#54A0FF" },
  school:    { label: "School",       emoji: "🏫", color: "#5F27CD" },
  body:      { label: "Body Parts",   emoji: "💪", color: "#01CBC6" },
  feelings:  { label: "Feelings",     emoji: "😊", color: "#EE5A24" },
  actions:   { label: "Actions",      emoji: "🏃", color: "#009432" },
};
